import { createContext, useContext, useState, ReactNode, useEffect } from 'react';

type Language = 'en' | 'fr' | 'es' | 'de' | 'zh' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Header & Navigation
    'nav.deals': '🔥 Deals',
    'nav.gold': 'Gold',
    'nav.silver': 'Silver',
    'nav.platinum': 'Platinum & Palladium',
    'nav.charts': 'Live Charts',
    'nav.priceList': 'Price List',
    'nav.resources': 'Resources',
    'header.needHelp': 'Need help?',
    'header.signIn': 'Sign in',
    'header.signOut': 'Sign out',
    'header.dashboard': 'Dashboard',
    'header.adminPanel': 'Admin Panel',
    'header.menu': 'Menu',
    'header.search': 'Search gold, silver, platinum...',
    'header.searchProducts': 'Search products...',
    
    // Home Page
    'home.hero.title': 'Invest in Precious Metals',
    'home.hero.subtitle': 'Secure your wealth with gold, silver, and platinum',
    'home.hero.cta': 'Start Investing',
    'home.stats.customers': 'Trusted Customers',
    'home.stats.products': 'Premium Products',
    'home.stats.countries': 'Countries Served',
    'home.stats.security': 'Secure Storage',
    
    // Products
    'products.title': 'Our Products',
    'products.filter': 'Filter',
    'products.sort': 'Sort by',
    'products.addToCart': 'Add to Cart',
    'products.viewDetails': 'View Details',
    'products.inStock': 'In Stock',
    'products.outOfStock': 'Out of Stock',
    
    // Cart
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continueShopping': 'Continue Shopping',
    'cart.browseProducts': 'Browse Products',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.insurance': 'Insurance',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.remove': 'Remove',
    'cart.quantity': 'Quantity',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.portfolio': 'My Portfolio',
    'dashboard.orders': 'My Orders',
    'dashboard.settings': 'Settings',
    'dashboard.totalValue': 'Total Portfolio Value',
    'dashboard.monthlyGrowth': 'Monthly Growth',
    
    // Footer
    'footer.newsletter.title': 'Stay Updated with Market Insights',
    'footer.newsletter.subtitle': 'Get exclusive market analysis, precious metals insights, and early access to new products.',
    'footer.newsletter.email': 'Enter your email',
    'footer.newsletter.subscribe': 'Subscribe',
    'footer.newsletter.success': 'Thank you for subscribing!',
    'footer.newsletter.successDesc': "You'll receive our latest market insights and exclusive offers.",
    'footer.company.title': 'Company',
    'footer.company.about': 'About Us',
    'footer.company.story': 'Our Story',
    'footer.company.careers': 'Careers',
    'footer.company.press': 'Press',
    'footer.company.blog': 'Blog',
    'footer.company.investors': 'Investors',
    'footer.products.title': 'Products',
    'footer.products.goldBars': 'Gold Bars',
    'footer.products.goldCoins': 'Gold Coins',
    'footer.products.silverBars': 'Silver Bars',
    'footer.products.silverCoins': 'Silver Coins',
    'footer.products.platinum': 'Platinum Products',
    'footer.products.palladium': 'Palladium Products',
    'footer.support.title': 'Support',
    'footer.support.helpCenter': 'Help Center',
    'footer.support.contact': 'Contact Us',
    'footer.support.shipping': 'Shipping Info',
    'footer.support.returns': 'Returns',
    'footer.support.track': 'Track Order',
    'footer.support.faq': 'FAQ',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Terms of Service',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.legal.compliance': 'Compliance',
    'footer.legal.security': 'Security',
    'footer.legal.notice': 'Legal Notice',
    'footer.description': 'Your trusted partner in precious metals investment. We provide secure storage, instant buyback, and transparent pricing for gold, silver, platinum, and palladium.',
    'footer.trust.security': 'Swiss Bank-Level Security',
    'footer.trust.certified': 'Certified Precious Metals',
    'footer.trust.pricing': 'Instant Market Pricing',
    'footer.followUs': 'Follow us:',
    'footer.copyright': '© 2024 Gold Avenue. All rights reserved. | Regulated by Swiss Financial Market Supervisory Authority (FINMA)',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.search': 'Search',
  },
  fr: {
    // Header & Navigation
    'nav.deals': '🔥 Offres',
    'nav.gold': 'Or',
    'nav.silver': 'Argent',
    'nav.platinum': 'Platine & Palladium',
    'nav.charts': 'Graphiques en Direct',
    'nav.priceList': 'Liste des Prix',
    'nav.resources': 'Ressources',
    'header.needHelp': 'Besoin d\'aide?',
    'header.signIn': 'Se connecter',
    'header.signOut': 'Se déconnecter',
    'header.dashboard': 'Tableau de bord',
    'header.adminPanel': 'Panneau Admin',
    'header.menu': 'Menu',
    'header.search': 'Rechercher or, argent, platine...',
    'header.searchProducts': 'Rechercher des produits...',
    
    // Home Page
    'home.hero.title': 'Investir dans les Métaux Précieux',
    'home.hero.subtitle': 'Sécurisez votre richesse avec l\'or, l\'argent et le platine',
    'home.hero.cta': 'Commencer à Investir',
    'home.stats.customers': 'Clients de Confiance',
    'home.stats.products': 'Produits Premium',
    'home.stats.countries': 'Pays Servis',
    'home.stats.security': 'Stockage Sécurisé',
    
    // Products
    'products.title': 'Nos Produits',
    'products.filter': 'Filtrer',
    'products.sort': 'Trier par',
    'products.addToCart': 'Ajouter au Panier',
    'products.viewDetails': 'Voir les Détails',
    'products.inStock': 'En Stock',
    'products.outOfStock': 'Rupture de Stock',
    
    // Cart
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.continueShopping': 'Continuer les Achats',
    'cart.browseProducts': 'Parcourir les Produits',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Livraison',
    'cart.insurance': 'Assurance',
    'cart.tax': 'Taxe',
    'cart.total': 'Total',
    'cart.checkout': 'Passer à la Caisse',
    'cart.remove': 'Supprimer',
    'cart.quantity': 'Quantité',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenue',
    'dashboard.portfolio': 'Mon Portefeuille',
    'dashboard.orders': 'Mes Commandes',
    'dashboard.settings': 'Paramètres',
    'dashboard.totalValue': 'Valeur Totale du Portefeuille',
    'dashboard.monthlyGrowth': 'Croissance Mensuelle',
    
    // Footer
    'footer.newsletter.title': 'Restez Informé des Tendances du Marché',
    'footer.newsletter.subtitle': 'Recevez des analyses exclusives, des informations sur les métaux précieux et un accès anticipé aux nouveaux produits.',
    'footer.newsletter.email': 'Entrez votre email',
    'footer.newsletter.subscribe': 'S\'abonner',
    'footer.newsletter.success': 'Merci de vous être abonné!',
    'footer.newsletter.successDesc': 'Vous recevrez nos dernières analyses de marché et offres exclusives.',
    'footer.company.title': 'Entreprise',
    'footer.company.about': 'À Propos',
    'footer.company.story': 'Notre Histoire',
    'footer.company.careers': 'Carrières',
    'footer.company.press': 'Presse',
    'footer.company.blog': 'Blog',
    'footer.company.investors': 'Investisseurs',
    'footer.products.title': 'Produits',
    'footer.products.goldBars': 'Lingots d\'Or',
    'footer.products.goldCoins': 'Pièces d\'Or',
    'footer.products.silverBars': 'Lingots d\'Argent',
    'footer.products.silverCoins': 'Pièces d\'Argent',
    'footer.products.platinum': 'Produits en Platine',
    'footer.products.palladium': 'Produits en Palladium',
    'footer.support.title': 'Support',
    'footer.support.helpCenter': 'Centre d\'Aide',
    'footer.support.contact': 'Nous Contacter',
    'footer.support.shipping': 'Info Livraison',
    'footer.support.returns': 'Retours',
    'footer.support.track': 'Suivre Commande',
    'footer.support.faq': 'FAQ',
    'footer.legal.privacy': 'Politique de Confidentialité',
    'footer.legal.terms': 'Conditions d\'Utilisation',
    'footer.legal.cookies': 'Politique des Cookies',
    'footer.legal.compliance': 'Conformité',
    'footer.legal.security': 'Sécurité',
    'footer.legal.notice': 'Mention Légale',
    'footer.description': 'Votre partenaire de confiance pour l\'investissement dans les métaux précieux. Nous offrons un stockage sécurisé, un rachat instantané et une tarification transparente pour l\'or, l\'argent, le platine et le palladium.',
    'footer.trust.security': 'Sécurité Niveau Banque Suisse',
    'footer.trust.certified': 'Métaux Précieux Certifiés',
    'footer.trust.pricing': 'Prix du Marché Instantané',
    'footer.followUs': 'Suivez-nous:',
    'footer.copyright': '© 2024 Gold Avenue. Tous droits réservés. | Réglementé par l\'Autorité fédérale de surveillance des marchés financiers (FINMA)',
    
    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.success': 'Succès',
    'common.cancel': 'Annuler',
    'common.save': 'Enregistrer',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.search': 'Rechercher',
  },
  es: {
    // Header & Navigation
    'nav.deals': '🔥 Ofertas',
    'nav.gold': 'Oro',
    'nav.silver': 'Plata',
    'nav.platinum': 'Platino y Paladio',
    'nav.charts': 'Gráficos en Vivo',
    'nav.priceList': 'Lista de Precios',
    'nav.resources': 'Recursos',
    'header.needHelp': '¿Necesitas ayuda?',
    'header.signIn': 'Iniciar sesión',
    'header.signOut': 'Cerrar sesión',
    'header.dashboard': 'Panel',
    'header.adminPanel': 'Panel de Admin',
    'header.menu': 'Menú',
    'header.search': 'Buscar oro, plata, platino...',
    'header.searchProducts': 'Buscar productos...',
    
    // Home Page
    'home.hero.title': 'Invertir en Metales Preciosos',
    'home.hero.subtitle': 'Asegure su riqueza con oro, plata y platino',
    'home.hero.cta': 'Comenzar a Invertir',
    'home.stats.customers': 'Clientes de Confianza',
    'home.stats.products': 'Productos Premium',
    'home.stats.countries': 'Países Servidos',
    'home.stats.security': 'Almacenamiento Seguro',
    
    // Products
    'products.title': 'Nuestros Productos',
    'products.filter': 'Filtrar',
    'products.sort': 'Ordenar por',
    'products.addToCart': 'Añadir al Carrito',
    'products.viewDetails': 'Ver Detalles',
    'products.inStock': 'En Stock',
    'products.outOfStock': 'Agotado',
    
    // Cart
    'cart.title': 'Carrito de Compras',
    'cart.empty': 'Tu carrito está vacío',
    'cart.continueShopping': 'Continuar Comprando',
    'cart.browseProducts': 'Explorar Productos',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Envío',
    'cart.insurance': 'Seguro',
    'cart.tax': 'Impuesto',
    'cart.total': 'Total',
    'cart.checkout': 'Proceder al Pago',
    'cart.remove': 'Eliminar',
    'cart.quantity': 'Cantidad',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido',
    'dashboard.portfolio': 'Mi Portafolio',
    'dashboard.orders': 'Mis Pedidos',
    'dashboard.settings': 'Configuración',
    'dashboard.totalValue': 'Valor Total del Portafolio',
    'dashboard.monthlyGrowth': 'Crecimiento Mensual',
    
    // Footer
    'footer.newsletter.title': 'Manténgase Actualizado con Perspectivas del Mercado',
    'footer.newsletter.subtitle': 'Reciba análisis exclusivos del mercado, información sobre metales preciosos y acceso anticipado a nuevos productos.',
    'footer.newsletter.email': 'Ingrese su email',
    'footer.newsletter.subscribe': 'Suscribirse',
    'footer.newsletter.success': '¡Gracias por suscribirse!',
    'footer.newsletter.successDesc': 'Recibirá nuestras últimas perspectivas del mercado y ofertas exclusivas.',
    'footer.company.title': 'Empresa',
    'footer.company.about': 'Sobre Nosotros',
    'footer.company.story': 'Nuestra Historia',
    'footer.company.careers': 'Carreras',
    'footer.company.press': 'Prensa',
    'footer.company.blog': 'Blog',
    'footer.company.investors': 'Inversores',
    'footer.products.title': 'Productos',
    'footer.products.goldBars': 'Barras de Oro',
    'footer.products.goldCoins': 'Monedas de Oro',
    'footer.products.silverBars': 'Barras de Plata',
    'footer.products.silverCoins': 'Monedas de Plata',
    'footer.products.platinum': 'Productos de Platino',
    'footer.products.palladium': 'Productos de Paladio',
    'footer.support.title': 'Soporte',
    'footer.support.helpCenter': 'Centro de Ayuda',
    'footer.support.contact': 'Contáctenos',
    'footer.support.shipping': 'Info de Envío',
    'footer.support.returns': 'Devoluciones',
    'footer.support.track': 'Rastrear Pedido',
    'footer.support.faq': 'Preguntas Frecuentes',
    'footer.legal.privacy': 'Política de Privacidad',
    'footer.legal.terms': 'Términos de Servicio',
    'footer.legal.cookies': 'Política de Cookies',
    'footer.legal.compliance': 'Cumplimiento',
    'footer.legal.security': 'Seguridad',
    'footer.legal.notice': 'Aviso Legal',
    'footer.description': 'Su socio de confianza en inversión de metales preciosos. Ofrecemos almacenamiento seguro, recompra instantánea y precios transparentes para oro, plata, platino y paladio.',
    'footer.trust.security': 'Seguridad a Nivel Bancario Suizo',
    'footer.trust.certified': 'Metales Preciosos Certificados',
    'footer.trust.pricing': 'Precios de Mercado Instantáneos',
    'footer.followUs': 'Síguenos:',
    'footer.copyright': '© 2024 Gold Avenue. Todos los derechos reservados. | Regulado por la Autoridad Supervisora del Mercado Financiero Suizo (FINMA)',
    
    // Common
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.previous': 'Anterior',
    'common.search': 'Buscar',
  },
  de: {
    // Header & Navigation
    'nav.deals': '🔥 Angebote',
    'nav.gold': 'Gold',
    'nav.silver': 'Silber',
    'nav.platinum': 'Platin & Palladium',
    'nav.charts': 'Live-Charts',
    'nav.priceList': 'Preisliste',
    'nav.resources': 'Ressourcen',
    'header.needHelp': 'Brauchen Sie Hilfe?',
    'header.signIn': 'Anmelden',
    'header.signOut': 'Abmelden',
    'header.dashboard': 'Dashboard',
    'header.adminPanel': 'Admin-Panel',
    'header.menu': 'Menü',
    'header.search': 'Gold, Silber, Platin suchen...',
    'header.searchProducts': 'Produkte suchen...',
    
    // Home Page
    'home.hero.title': 'In Edelmetalle Investieren',
    'home.hero.subtitle': 'Sichern Sie Ihr Vermögen mit Gold, Silber und Platin',
    'home.hero.cta': 'Jetzt Investieren',
    'home.stats.customers': 'Vertrauenswürdige Kunden',
    'home.stats.products': 'Premium-Produkte',
    'home.stats.countries': 'Länder Bedient',
    'home.stats.security': 'Sichere Lagerung',
    
    // Products
    'products.title': 'Unsere Produkte',
    'products.filter': 'Filtern',
    'products.sort': 'Sortieren nach',
    'products.addToCart': 'In den Warenkorb',
    'products.viewDetails': 'Details Anzeigen',
    'products.inStock': 'Auf Lager',
    'products.outOfStock': 'Nicht Vorrätig',
    
    // Cart
    'cart.title': 'Warenkorb',
    'cart.empty': 'Ihr Warenkorb ist leer',
    'cart.continueShopping': 'Weiter Einkaufen',
    'cart.browseProducts': 'Produkte Durchsuchen',
    'cart.subtotal': 'Zwischensumme',
    'cart.shipping': 'Versand',
    'cart.insurance': 'Versicherung',
    'cart.tax': 'Steuer',
    'cart.total': 'Gesamt',
    'cart.checkout': 'Zur Kasse',
    'cart.remove': 'Entfernen',
    'cart.quantity': 'Menge',
    
    // Dashboard
    'dashboard.welcome': 'Willkommen zurück',
    'dashboard.portfolio': 'Mein Portfolio',
    'dashboard.orders': 'Meine Bestellungen',
    'dashboard.settings': 'Einstellungen',
    'dashboard.totalValue': 'Gesamtwert des Portfolios',
    'dashboard.monthlyGrowth': 'Monatliches Wachstum',
    
    // Footer
    'footer.newsletter.title': 'Bleiben Sie mit Markteinblicken auf dem Laufenden',
    'footer.newsletter.subtitle': 'Erhalten Sie exklusive Marktanalysen, Einblicke in Edelmetalle und frühzeitigen Zugang zu neuen Produkten.',
    'footer.newsletter.email': 'E-Mail eingeben',
    'footer.newsletter.subscribe': 'Abonnieren',
    'footer.newsletter.success': 'Vielen Dank für Ihr Abonnement!',
    'footer.newsletter.successDesc': 'Sie erhalten unsere neuesten Markteinblicke und exklusiven Angebote.',
    'footer.company.title': 'Unternehmen',
    'footer.company.about': 'Über Uns',
    'footer.company.story': 'Unsere Geschichte',
    'footer.company.careers': 'Karriere',
    'footer.company.press': 'Presse',
    'footer.company.blog': 'Blog',
    'footer.company.investors': 'Investoren',
    'footer.products.title': 'Produkte',
    'footer.products.goldBars': 'Goldbarren',
    'footer.products.goldCoins': 'Goldmünzen',
    'footer.products.silverBars': 'Silberbarren',
    'footer.products.silverCoins': 'Silbermünzen',
    'footer.products.platinum': 'Platinprodukte',
    'footer.products.palladium': 'Palladiumprodukte',
    'footer.support.title': 'Support',
    'footer.support.helpCenter': 'Hilfezentrum',
    'footer.support.contact': 'Kontaktieren Sie Uns',
    'footer.support.shipping': 'Versandinfo',
    'footer.support.returns': 'Rücksendungen',
    'footer.support.track': 'Bestellung Verfolgen',
    'footer.support.faq': 'FAQ',
    'footer.legal.privacy': 'Datenschutz',
    'footer.legal.terms': 'Nutzungsbedingungen',
    'footer.legal.cookies': 'Cookie-Richtlinie',
    'footer.legal.compliance': 'Compliance',
    'footer.legal.security': 'Sicherheit',
    'footer.legal.notice': 'Impressum',
    'footer.description': 'Ihr vertrauenswürdiger Partner für Edelmetallinvestitionen. Wir bieten sichere Lagerung, sofortigen Rückkauf und transparente Preise für Gold, Silber, Platin und Palladium.',
    'footer.trust.security': 'Schweizer Bank-Sicherheitsniveau',
    'footer.trust.certified': 'Zertifizierte Edelmetalle',
    'footer.trust.pricing': 'Sofortige Marktpreise',
    'footer.followUs': 'Folgen Sie uns:',
    'footer.copyright': '© 2024 Gold Avenue. Alle Rechte vorbehalten. | Reguliert durch die Eidgenössische Finanzmarktaufsicht (FINMA)',
    
    // Common
    'common.loading': 'Laden...',
    'common.error': 'Fehler',
    'common.success': 'Erfolg',
    'common.cancel': 'Abbrechen',
    'common.save': 'Speichern',
    'common.delete': 'Löschen',
    'common.edit': 'Bearbeiten',
    'common.view': 'Ansehen',
    'common.back': 'Zurück',
    'common.next': 'Weiter',
    'common.previous': 'Zurück',
    'common.search': 'Suchen',
  },
  zh: {
    // Header & Navigation
    'nav.deals': '🔥 优惠',
    'nav.gold': '黄金',
    'nav.silver': '白银',
    'nav.platinum': '铂金和钯金',
    'nav.charts': '实时图表',
    'nav.priceList': '价格表',
    'nav.resources': '资源',
    'header.needHelp': '需要帮助？',
    'header.signIn': '登录',
    'header.signOut': '退出',
    'header.dashboard': '仪表板',
    'header.adminPanel': '管理面板',
    'header.menu': '菜单',
    'header.search': '搜索黄金、白银、铂金...',
    'header.searchProducts': '搜索产品...',
    
    // Home Page
    'home.hero.title': '投资贵金属',
    'home.hero.subtitle': '用黄金、白银和铂金保护您的财富',
    'home.hero.cta': '开始投资',
    'home.stats.customers': '信赖的客户',
    'home.stats.products': '优质产品',
    'home.stats.countries': '服务国家',
    'home.stats.security': '安全存储',
    
    // Products
    'products.title': '我们的产品',
    'products.filter': '筛选',
    'products.sort': '排序',
    'products.addToCart': '加入购物车',
    'products.viewDetails': '查看详情',
    'products.inStock': '有货',
    'products.outOfStock': '缺货',
    
    // Cart
    'cart.title': '购物车',
    'cart.empty': '您的购物车是空的',
    'cart.continueShopping': '继续购物',
    'cart.browseProducts': '浏览产品',
    'cart.subtotal': '小计',
    'cart.shipping': '运费',
    'cart.insurance': '保险',
    'cart.tax': '税费',
    'cart.total': '总计',
    'cart.checkout': '结账',
    'cart.remove': '删除',
    'cart.quantity': '数量',
    
    // Dashboard
    'dashboard.welcome': '欢迎回来',
    'dashboard.portfolio': '我的投资组合',
    'dashboard.orders': '我的订单',
    'dashboard.settings': '设置',
    'dashboard.totalValue': '投资组合总值',
    'dashboard.monthlyGrowth': '月增长',
    
    // Footer
    'footer.newsletter.title': '获取市场洞察更新',
    'footer.newsletter.subtitle': '获取独家市场分析、贵金属见解和新产品的早期访问权。',
    'footer.newsletter.email': '输入您的电子邮件',
    'footer.newsletter.subscribe': '订阅',
    'footer.newsletter.success': '感谢您订阅！',
    'footer.newsletter.successDesc': '您将收到我们最新的市场洞察和独家优惠。',
    'footer.company.title': '公司',
    'footer.company.about': '关于我们',
    'footer.company.story': '我们的故事',
    'footer.company.careers': '职业',
    'footer.company.press': '新闻',
    'footer.company.blog': '博客',
    'footer.company.investors': '投资者',
    'footer.products.title': '产品',
    'footer.products.goldBars': '金条',
    'footer.products.goldCoins': '金币',
    'footer.products.silverBars': '银条',
    'footer.products.silverCoins': '银币',
    'footer.products.platinum': '铂金产品',
    'footer.products.palladium': '钯金产品',
    'footer.support.title': '支持',
    'footer.support.helpCenter': '帮助中心',
    'footer.support.contact': '联系我们',
    'footer.support.shipping': '运输信息',
    'footer.support.returns': '退货',
    'footer.support.track': '跟踪订单',
    'footer.support.faq': '常见问题',
    'footer.legal.privacy': '隐私政策',
    'footer.legal.terms': '服务条款',
    'footer.legal.cookies': 'Cookie政策',
    'footer.legal.compliance': '合规',
    'footer.legal.security': '安全',
    'footer.legal.notice': '法律声明',
    'footer.description': '您值得信赖的贵金属投资合作伙伴。我们为黄金、白银、铂金和钯金提供安全存储、即时回购和透明定价。',
    'footer.trust.security': '瑞士银行级安全',
    'footer.trust.certified': '认证贵金属',
    'footer.trust.pricing': '即时市场定价',
    'footer.followUs': '关注我们：',
    'footer.copyright': '© 2024 Gold Avenue. 保留所有权利。| 受瑞士金融市场监督管理局（FINMA）监管',
    
    // Common
    'common.loading': '加载中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.cancel': '取消',
    'common.save': '保存',
    'common.delete': '删除',
    'common.edit': '编辑',
    'common.view': '查看',
    'common.back': '返回',
    'common.next': '下一步',
    'common.previous': '上一步',
    'common.search': '搜索',
  },
  it: {
    // Header & Navigation
    'nav.deals': '🔥 Offerte',
    'nav.gold': 'Oro',
    'nav.silver': 'Argento',
    'nav.platinum': 'Platino e Palladio',
    'nav.charts': 'Grafici in Tempo Reale',
    'nav.priceList': 'Listino Prezzi',
    'nav.resources': 'Risorse',
    'header.needHelp': 'Hai bisogno di aiuto?',
    'header.signIn': 'Accedi',
    'header.signOut': 'Esci',
    'header.dashboard': 'Dashboard',
    'header.adminPanel': 'Pannello Admin',
    'header.menu': 'Menu',
    'header.search': 'Cerca oro, argento, platino...',
    'header.searchProducts': 'Cerca prodotti...',
    
    // Home Page
    'home.hero.title': 'Investi in Metalli Preziosi',
    'home.hero.subtitle': 'Proteggi la tua ricchezza con oro, argento e platino',
    'home.hero.cta': 'Inizia a Investire',
    'home.stats.customers': 'Clienti Fidati',
    'home.stats.products': 'Prodotti Premium',
    'home.stats.countries': 'Paesi Serviti',
    'home.stats.security': 'Deposito Sicuro',
    
    // Products
    'products.title': 'I Nostri Prodotti',
    'products.filter': 'Filtra',
    'products.sort': 'Ordina per',
    'products.addToCart': 'Aggiungi al Carrello',
    'products.viewDetails': 'Vedi Dettagli',
    'products.inStock': 'Disponibile',
    'products.outOfStock': 'Esaurito',
    
    // Cart
    'cart.title': 'Carrello',
    'cart.empty': 'Il tuo carrello è vuoto',
    'cart.continueShopping': 'Continua gli Acquisti',
    'cart.browseProducts': 'Sfoglia Prodotti',
    'cart.subtotal': 'Subtotale',
    'cart.shipping': 'Spedizione',
    'cart.insurance': 'Assicurazione',
    'cart.tax': 'Tassa',
    'cart.total': 'Totale',
    'cart.checkout': 'Procedi al Pagamento',
    'cart.remove': 'Rimuovi',
    'cart.quantity': 'Quantità',
    
    // Dashboard
    'dashboard.welcome': 'Bentornato',
    'dashboard.portfolio': 'Il Mio Portfolio',
    'dashboard.orders': 'I Miei Ordini',
    'dashboard.settings': 'Impostazioni',
    'dashboard.totalValue': 'Valore Totale del Portfolio',
    'dashboard.monthlyGrowth': 'Crescita Mensile',
    
    // Footer
    'footer.newsletter.title': 'Rimani Aggiornato sulle Tendenze del Mercato',
    'footer.newsletter.subtitle': 'Ricevi analisi esclusive del mercato, informazioni sui metalli preziosi e accesso anticipato ai nuovi prodotti.',
    'footer.newsletter.email': 'Inserisci la tua email',
    'footer.newsletter.subscribe': 'Iscriviti',
    'footer.newsletter.success': 'Grazie per esserti iscritto!',
    'footer.newsletter.successDesc': 'Riceverai le nostre ultime analisi di mercato e offerte esclusive.',
    'footer.company.title': 'Azienda',
    'footer.company.about': 'Chi Siamo',
    'footer.company.story': 'La Nostra Storia',
    'footer.company.careers': 'Carriere',
    'footer.company.press': 'Stampa',
    'footer.company.blog': 'Blog',
    'footer.company.investors': 'Investitori',
    'footer.products.title': 'Prodotti',
    'footer.products.goldBars': 'Lingotti d\'Oro',
    'footer.products.goldCoins': 'Monete d\'Oro',
    'footer.products.silverBars': 'Lingotti d\'Argento',
    'footer.products.silverCoins': 'Monete d\'Argento',
    'footer.products.platinum': 'Prodotti in Platino',
    'footer.products.palladium': 'Prodotti in Palladio',
    'footer.support.title': 'Supporto',
    'footer.support.helpCenter': 'Centro Assistenza',
    'footer.support.contact': 'Contattaci',
    'footer.support.shipping': 'Info Spedizione',
    'footer.support.returns': 'Resi',
    'footer.support.track': 'Traccia Ordine',
    'footer.support.faq': 'FAQ',
    'footer.legal.privacy': 'Privacy Policy',
    'footer.legal.terms': 'Termini di Servizio',
    'footer.legal.cookies': 'Cookie Policy',
    'footer.legal.compliance': 'Conformità',
    'footer.legal.security': 'Sicurezza',
    'footer.legal.notice': 'Note Legali',
    'footer.description': 'Il tuo partner di fiducia per gli investimenti in metalli preziosi. Offriamo deposito sicuro, riacquisto immediato e prezzi trasparenti per oro, argento, platino e palladio.',
    'footer.trust.security': 'Sicurezza a Livello Bancario Svizzero',
    'footer.trust.certified': 'Metalli Preziosi Certificati',
    'footer.trust.pricing': 'Prezzi di Mercato Istantanei',
    'footer.followUs': 'Seguici:',
    'footer.copyright': '© 2024 Gold Avenue. Tutti i diritti riservati. | Regolato dall\'Autorità federale di vigilanza sui mercati finanziari (FINMA)',
    
    // Common
    'common.loading': 'Caricamento...',
    'common.error': 'Errore',
    'common.success': 'Successo',
    'common.cancel': 'Annulla',
    'common.save': 'Salva',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.view': 'Visualizza',
    'common.back': 'Indietro',
    'common.next': 'Avanti',
    'common.previous': 'Precedente',
    'common.search': 'Cerca',
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
