// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://evhnpcssaivmiywecpck.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2aG5wY3NzYWl2bWl5d2VjcGNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwODk4MzAsImV4cCI6MjA3NDY2NTgzMH0.m7aEantCX9xTREZmIMNKUNv6rXJxKb-tEfyDKAreyvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});